### ISSUE TITLE
UnicodeEncodeError on link export

### ISSUE THREAD

**Issue by zidz** [rawler/bhindex#10]
I tested a few things also but was unsuccessful fixing the problem for the time being.
One possible solution that I don't have time to test right now is using this:
https://pythonhosted.org/kitchen/api-text-converters.html#kitchen.text.converters.getwriter

Traceback (most recent call last):
File "./bhindex.py", line 5, in
bhindex.main(sys.argv[1:])
File "/opt/bithorde/bhindex/bhindex/init.py", line 62, in main
args.main(args, cfg, db)
File "/opt/bithorde/bhindex/bhindex/links.py", line 171, in main
return export(db, bithorde, args.output_dir, args.target_dir, args.prefix, args.force_all)
File "/opt/bithorde/bhindex/bhindex/links.py", line 142, in export
count, size = DBExporter(db, bithorde, tgt).export(force_all)
File "/opt/bithorde/bhindex/bhindex/links.py", line 114, in export
if self.write_links(obj):
File "/opt/bithorde/bhindex/bhindex/links.py", line 100, in write_links
return all(self.tgt("/".join(p), tgt) for p in self.fs.paths_for(obj))
File "/opt/bithorde/bhindex/bhindex/links.py", line 100, in
return all(self.tgt("/".join(p), tgt) for p in self.fs.paths_for(obj))
File "/opt/bithorde/bhindex/bhindex/links.py", line 41, in call
print u"Linking %s -> %s".encode('utf8') % (p, t)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 22: ordinal not in range(128)

**Comment by rawler** [comment]
I believe this to be solved in master as of 5930703

**Comment by zidz** [comment]
Yes, thanks
