### ISSUE TITLE
Bhindex crash

### ISSUE THREAD

**Issue by Jenkler** [rawler/bhindex#12]
Running: /usr/bin/bhindex link

Links gets created but when complete I get this!

Traceback (most recent call last):
  File "/usr/bin/bhindex", line 9, in <module>
    load_entry_point('bhindex==0.7', 'console_scripts', 'bhindex')()
  File "/usr/lib/python2.7/dist-packages/bhindex/__init__.py", line 75, in main
    args.main(*main_args)
  File "/usr/lib/python2.7/dist-packages/bhindex/links.py", line 174, in main
    return export(db, bithorde, args.output_dir, args.target_dir, args.prefix, args.force_all)
  File "/usr/lib/python2.7/dist-packages/bhindex/links.py", line 145, in export
    count, size = DBExporter(db, bithorde, tgt).export(force_all)
  File "/usr/lib/python2.7/dist-packages/bhindex/links.py", line 117, in export
    if self.write_links(obj):
  File "/usr/lib/python2.7/dist-packages/bhindex/links.py", line 98, in write_links
    xt_spec = "&".join("xt=urn:" + xt for xt in obj['xt'])
  File "/usr/lib/python2.7/dist-packages/distdb/obj.py", line 72, in __getitem__
    return self._dict[key].v
KeyError: 'xt'

**Comment by rawler** [comment]
Not sure this is relevant anymore. Please reopen if still seen
