### ISSUE TITLE
global name 'log' is not defined

### ISSUE THREAD

**Issue by zidz** [rawler/bhindex#5]
Can't find any config for log in sample.config
How can I solve this issue?

Traceback (most recent call last):
  File "/opt/bithorde/bhindex/add.py", line 161, in <module>
    add(file, options.tags, options.exts)
  File "/opt/bithorde/bhindex/add.py", line 130, in add
    asset[u'directory'] = db.ValueSet(u"%s/%s" % (make_directory(DB, path_list[:-1], t), path_list[-1]), t)
  File "/opt/bithorde/bhindex/util.py", line 135, in make_directory
    dir_id = get_folder_id(db, dir_id, segment, t)
  File "/opt/bithorde/bhindex/util.py", line 123, in get_folder_id
    log.warning("Duplicate folders for %s" % directory_attr)
NameError: global name 'log' is not defined

**Comment by rawler** [comment]
It SHOULD be fixed in master since a couple of days?

**Comment by zidz** [comment]
I'll see if Puppet did fetch the latest git commit and come back.

**Comment by zidz** [comment]
Just an old version. Git pull solved the issue.
